### PR TITLE
Finsished till point 12.

### PR DESCRIPTION
**Pull request by HabibUrRehmanBhattii**
### 12. Add logics to Quiz Component 🧠
 -  [x] Add logic to check if answer is correct or not.
 -  [x] Save the score in a variable.
 -  [x] Display the score on the screen.
 -  [x] Add parse to parse the html code in the string and render it as html
 -  [x] Display the score in when the `Submit` button is clicked.
 -  [x] Replace the `Submit` button with `Play Again` button when the `Submit` button is clicked.
 -  [x] Add a Glow and confetti if the score is 5.
 -  [x] Render the score component.
 -  [x] Add logic to reset the score when the `Play Again` button is clicked.
 -  [x] When check Answer is clicked, disable the radio button.
 -  [x] When check Answer is clicked, show the correct answer.
 -  [x] When check Answer is clicked, if the answer is incorrect change the color of the label to red.
 -  [x] Randomize the answers.
 -  [x] Add loading when the data is being fetched.
 -  [x] Add a functional `Play Again` button

I have removed the randomized answer for testing. The last input is correct.
You can check result here 
https://gleaming-dragon-ea6f50.netlify.app/

### CODE REVIEW

**Comment by hmjatt** [comment]
Wow, this is amazing and preview looks great. I will randomize the answers today and make any changes that need be. I really appreciate your help with the project. Will be updating the footer of the app including your name as well. Have a great weekend 😄

**Comment by hmjatt** [comment]
Fixing some branch conflicts.

**Comment by HabibUrRehmanBhattii** [comment]
Just a update. Right now its not responsive to small devices

**Comment by HabibUrRehmanBhattii** [comment]
> Wow, this is amazing and preview looks great. I will randomize the answers today and make any changes that need be. I really appreciate your help with the project. Will be updating the footer of the app including your name as well. Have a great weekend smile

Thanks. You can randomize by removing the commented part from line 115
                        ) /*.sort(() => Math.random() - 0.5),*/ /* Randomize the answers */,

**Comment by hmjatt** [comment]
No worries, will be working on that next. Just finished randomizing the answers lol, anyways great work dude

**Comment by HabibUrRehmanBhattii** [comment]
I have a suggestion that we divide the Quiz.js into small components.

**Comment by hmjatt** [comment]
I agree and maybe get rid of some unused code. If you want to work on that let me know.

**Comment by HabibUrRehmanBhattii** [comment]
yes i will look into this and for practice run i am thinking to divide almost every section to its components. I think that is a main part of React. Its my thought

**Comment by hmjatt** [comment]
I am still pretty new to react, but I definitely agree. I will observe how you do it and will practice in my next project or if you want I can do some of it just so I got it right.

**Comment by HabibUrRehmanBhattii** [comment]
And we can also modified our style with advance CSS techniques.
We can use these techniques so CSS don't go out side of assigned component. It will only apply where we mention. this will help us with bug like repeating the classes.
 These are which i have heard of 
1.styled-components
[link](https://styled-components.com/)
2. CSS Module (It is a built feature )
[React Dos](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet)

!This is also brand new for me

**Comment by hmjatt** [comment]
It's pretty neat, just bookmarked them and can eventually divide CSS into components. I can see that we can use it in answers, maybe results and footer as well. Going to experiment with it right now

**Comment by HabibUrRehmanBhattii** [comment]
Can I use your Readme.md styles for my future projects?
Thanks in advance!

**Comment by hmjatt** [comment]
Yea for sure, no worries.

**Comment by hmjatt** [comment]
Just finished making app responsive, let me know if it looks good on your side. Going to start cleaning code tomorrow. If there are any issues let me know or raise a PR. Thanks a lot for your help again :D

**Pull request merged**
