### PR TITLE
Footer to slider, removed extra comments

### PR DESCRIPTION
**Pull request by HabibUrRehmanBhattii**

### CODE REVIEW

**Comment by HabibUrRehmanBhattii** [comment]
https://gifyu.com/image/SE63i

**Comment by HabibUrRehmanBhattii** [comment]
GIF . can be uploaded on readme.md

![like this]
(https://s1.gifyu.com/images/ezgif.com-gif-maker17089e18894031c8.gif)

put in one line

**Comment by hmjatt** [comment]
Nice thanks for that. Looks great. does the gif stay on their servers forever? if not i could upload it to repo in the project-output folder

**Comment by hmjatt** [comment]
I can preview the gif in my readme locally but it does not show on GitHub repo . Going to try uploading it to the repo and add a link to gif file and let's see how it goes.

**Comment by hmjatt** [comment]
Its working now

**Pull request merged**
